### ISSUE TITLE
Does this library support migration in case you change Object structure with the update?

### ISSUE THREAD

**Issue by klemenzagar91** [hyperoslo/Cache#153]
What happens if in app version 1.0 you have object:
```
Person {
   var fullname: String
}
```
and later in app version 2.0 you have:
```
Person {
   var firstname: String
   var lastname: String
}
```
1. Can you confirm that this wont crash.
2. Is it also posible to have a place where you do the migration for existing entities that exist from previous version? (for this example to split fullname John Doe into firstname John and lastname Doe)

**Comment by onmyway133** [comment]
@klemenzagar91 Interesting. How would you like to handle the migration?

**Comment by klemenzagar91** [comment]
Amm for now I like how Realm library handles it.
https://realm.io/docs/swift/latest/#migrations

**Comment by onmyway133** [comment]
@klemenzagar91 Hi, I added a test here to demo migration. It works similar to how Realm does. Basically, you cast to old object, migrate, then save the new object. What do you think?

**Comment by klemenzagar91** [comment]
Ok looks great. As far as I can see, the realm has a good approach how to trigger the migration. So when app creates a Realm configuration it also triggers migration, where you can go through iteration for the objects that has different structure. For the versioning I don't know if it also need to be implement here. 

Besides that this will be a very useful feature. For current project I already use Realm, but I'll use this one at next chance.

**Comment by onmyway133** [comment]
@klemenzagar91 Yeah, we can implement versioning to `Cache` that goes beyond the scope of the project. Looking forward to hearing your experience with `Cache` soon 👍

**Comment by zenangst** [comment]
Ohai folks, just thought I'd share my two cents on the subject. First of, comparing `Cache` and `Realm` feels a bit skewed to me as one is a relational database and other one is just a cache. Anything that is cached should be considered as discardable content when it has become outdated, hence the need for doing migrations should be zero. If the objects have changed and can no longer be decodable that would render them outdated in the same way as if the expiration date set on the cached object has passed. And yeah, the app should not crash because you change your models, if it does then that would be a bug in the framework :)
