### ISSUE TITLE
Disk and Memory Question

### ISSUE THREAD

**Issue by Lee827** [hyperoslo/Cache#177]
1.
That means the maximum size? in bytes? totalCostLimit:  100 * 8 * 1024 * 1024 = 100 MB?
Your example: totalCostLimit: 10
What is the size?
/// The maximum total cost that the cache can hold before it starts evicting objects
I don't understand that means?

2.
If the disk already full size, cannot cache anything? or remove the old cache? (set no expiry date)

Thank you!

**Comment by guoyingtao** [comment]
1. The totalCostLimit should be in bytes and it's a property of NSCache. I don't think this totalCostLimit would work since when putting objects into the cache, the cost of every object is not assigned.
2. You can check removeResourceObjects. When storage size exceeds max size, it will remove old objects until the size is below the half of max size.
