### ISSUE TITLE
[5.0.0] Why is memoryConfig no longer optional? 

### ISSUE THREAD

**Issue by RamblinWreck77** [hyperoslo/Cache#191]
Hello! Checking out the new release it seems memory config is no longer optional, is this intentional?

I use cache to write codable types to disk, and don't want to have any memory caching at all. 

Also, what's up with transformer here:

```
let storage = try? Storage(
  diskConfig: diskConfig, 
  memoryConfig: memoryConfig, 
  transformer: TransformerFactory.forCodable(ofType: User.self) // Storage<User>
)
```

Does this mean you need separate storage instances for each type? If so this seems like huge step back. If we're already enforcing Codable, why is the entire transformer process required at all?

**Comment by onmyway133** [comment]
@RamblinWreck77 You need separated instance of storage for each type, but under the hood they all save to the same location. The reason we can't support MemoryStorage right now is due to `associated protocols`. However, we public all the `Storage` classes so you can combine them the way you want. The default `Storage` class always uses hybrid storage

**Comment by RamblinWreck77** [comment]
So what's the best way to configure the memory cache size to be zero?

I don't want anything "floating" in memory, I'd like all cached values to go to disk immediately.
