### ISSUE TITLE
Why are all Issues and PR's closed?

### ISSUE THREAD

**Issue by evermeer** [hyperoslo/Cache#258]
Are you planning a fresh start with the library?
Those issues are still issues.
It would only be useful If you also rebuild the code from scratch.

**Comment by 3lvis** [comment]
Hi @evermeer! Trying to get a grip on this project, maintaining an abandoned project is a big challenge. I believe that rather than letting this project die it was worth it to give it a fresh start and focus on the issues that the current and new users have rather than keeping baggage of issues that might not be relevant anymore.

I'm open to reopen, revisit, and fix any past bugs that still exist. If you have anything in specific let me know.

**Comment by evermeer** [comment]
Great to hear you are planning a restart!
I'm still using it in a production app.
For the issues I had I am now using workarounds.
Or you could say by now those ar implementations the library need :-)

**Comment by 3lvis** [comment]
Thank you for your understanding, hope you and your family stay safe. If you need any help just ping me. Have a great day!

**Comment by wongzigii** [comment]
@3lvis Keep moving! Thanks
